#!/bin/bash
cleanupDirectory=$1

# check if the argument in the directory exists
if [[ -z "$cleanupDirectory" ]]
then 
	echo "Need to pass a directory path as argument."
	exit 0
elif [[ -d $1 ]]
then 
	echo "$cleanupDirectory found."
else 
	echo "$cleanupDirectory does not exist on your file system"
	exit 0
fi

readonly pictureDir=~/Pictures
#change the seconds to 3 days
readonly pictureOlderThan=2000

#function that will evaluate file types
function evalFile() {
	if [[ $(file -b $1) =~ JPEG ]] || [[ $(file -b $1) =~ PNG ]] ;
	then 
		lastModificationDate=$(date +%s -r $1)
		currentDate=$(date +%s)
		elapsedTime=$((currentDate - lastModificationDate))
		if [[ $elapsedTime -gt $pictureOlderThan ]]; then
			MES=$(LANG=en_us_88591; date +"%b")
			desDir="$pictureDir/$MES"
			if [[ -d "$desDir" ]]
			then 
				moveToPictures="mv $1 $desDir"
				eval $moveToPictures && echo "Moved $1 to $desDir"	
			else 
				echo "Making directory $MES in $pictureDir"
				mkdir $desDir
				moveToPictures="mv $1 $desDir"
				eval $moveToPictures && echo "Moved $1 to $desDir"	
			fi 
			

		fi	
	
	fi
}

#aksjdfaklsjdfoop through each file in directory passed as an argument and execute them to te function evalFile
for file in $1/*; do
	evalFile "$file"
done

# Now sending files to corresponding directories under Month.
# If Deb files are older than 10 days, they should be deleted.
# Learn to how to maintain a log file.
# Time period for a file to stay in the directory is now a constant in the script. Make it read as argument 
