#!/bin/bash
cleanupDirectory=$1

# check if the argument in the directory exists
if [[ -z "$cleanupDirectory" ]]
then 
	echo "Need to pass a directory path as argument."
	exit 0
elif [[ -d $1 ]]
then 
	echo "$cleanupDirectory found."
else 
	echo "$cleanupDirectory does not exist on your file system"
	exit 0
fi

readonly pictureFolder=~/Pictures
readonly pictureOlderThan=2000

#function that will evaluate file types
function evalFile() {
	if [[ $(file -b $1) =~ JPEG ]] || [[ $(file -b $1) =~ PNG ]] ;
	then 
		lastModificationDate=$(date +%s -r $1)
		currentDate=$(date +%s)
		elapsedTime=$((currentDate - lastModificationDate))
		if [[ $elapsedTime -gt $pictureOlderThan ]]; then
			moveToPictures="mv $1 $pictureFolder"
			eval $moveToPictures && echo "Moved $1 to $pictureFolder"

		fi	
	
	fi
}

#loop through each file in directory passed as an argument and execute them to te function evalFile
for file in $1/*; do
	evalFile "$file"
done

# Files will be sent to their corresponding directories e.g. jpg and png images to ~Pictures and will be sorted in order of month it was downloaded in. answer is here https://unix.stackexchange.com/questions/470517/check-a-file-is-created-on-current-month
# If Deb files are older than 10 days, they should be deleted.
# Learn to how to maintain a log file.
# Time period for a file to stay in the directory is now a constant in the script. Make it read as argument 
